# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MarkLees'Blog  #博客名
subtitle:    #博客副标题
description: 反手就是一张过去的CD~  #网站描述, 用于爬虫抓取的关键词,可以不填
keywords: hexo,hexo-blog,hexo-theme-next,前端web,HTML,CSS,JavaScript   #网站关键字
author: markLee      #作者名称
language:          #网页编码,中文
  - zh-CN
  # - zh-TW
  # - en     
  # - ja
  # - ko      
timezone: Asia/Shanghai      #站点时区，默认电脑时间

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# 如果网址是次级目录，比如：http://example.com/blog，
# 那么就要设置`url`为`http://example.com/blog`，并且`root`要设置为`/blog/`
url: https://www.marklee.top/    # 用于绑定域名, 其他的不需要配置
root: /       # 站点根目录
# 博客文章的 URL 结构，请务必写文章之前就想好！
# 详细参数请查看：https://hexo.io/docs/permalinks.html
permalink: :title/ #文章的永久链接格式
permalink_defaults:

# 目录配置
# Directory
source_dir: source          #资源文件夹,用于存放内容
public_dir: public          #公共文件夹,用于存放生成的站点文件
tag_dir: tags               #标签文件夹
archive_dir: archives       #归档文件夹
category_dir: categories    #分类文件夹
code_dir: downloads/code    #include code文件夹
i18n_dir: :lang             #国际化(i18n)文件夹
#跳过指定文件的渲染,可使用glob表达式来匹配路径
#这两个文件是百度和google的站长验证文件，不能渲染，否则会改变内容，不能验证过
skip_render: [baidu_verify_R9MZjdMkXT.html, google0f8fac7da2b48ef8.html, README.md, 模板.md] 
## 默认情况下，Hexo生成的超链接都是绝对地址。
## 例如，如果您的网站域名为example.com,您有一篇文章名为hello，
## 那么绝对链接可能像这样：http://example.com/hello.html，
## 它是绝对于域名的。相对链接像这样：/hello.html，
## 也就是说，无论用什么域名访问该站点，都没有关系，
## 这在进行反向代理时可能用到。通常情况下，建议使用绝对地址。

# 写作配置
# Writing
new_post_name: :title.md # File name of new posts，新建文章默认文件名
default_layout: post  # 默认布局
titlecase: false    #把标题转为title case
external_link: true #在新标签中打开一个外部链接，默认为true
filename_case: 0 # 转换文件名，1代表小写；2代表大写；默认为0，意思就是创建文章的时候，是否自动帮你转换文件名，默认就行，
render_drafts: false  # 是否渲染_drafts目录下的文章，默认为false
post_asset_folder: false  # 是否启用Asset Folder，默认为false
relative_link: false
future: true  # 是否显示未来日期文章，默认为true
# 代码高亮设置
highlight:  
  enable: true
  line_number: true
  auto_detect: true  #代码自动高亮
  tab_replace:
  
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date
  
# Category & Tag分类和标签的设置：
# 默认分类，默认为无分类，当然你可以设置一个默认分类。
default_category: uncategorized  #默认分类
category_map:                    #分类别名
tag_map:                         #标签别名

# Archives
#Archives 默认值为2,修改为1,Archives页面就只会列出标题,而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server服务器设置, 不修改
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
# port: 4000
# server_ip: localhost
# logger: false
# logger_format: dev

# Date / Time format日期和时间格式配置：
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页配置
# ---------------下面选项需要对应插件的支持（已安装）---------------
# npm install hexo-generator-index --save
# npm install hexo-generator-archive --save
# npm install hexo-generator-category --save
# npm install hexo-generator-tag --save
index_generator:   #首页的分页设置
  per_page: 5
archive_generator: #归档页的分页设置
  per_page: 20
  yearly: true
  monthly: true
tag_generator:     #标签页的分页设置
  per_page: 20
# per_page: 10
# pagination_dir: pag

# Extensions
## Plugins: https://hexo.io/plugins/
plugins: 
baidusitemap: 
  path: baidusitemap.xml
# RSS，要先进入站点文件夹根目录安装插件
# npm install hexo-generator-feed --save 即可
# 无需更多配置
# 参数说明查看 README：https://github.com/hexojs/hexo-generator-feed
feed:  # 配置RSS
  type: atom    #feed 类型 (atom/rss2)
  path: atom.xml  #rss 路径
  limit: 0    #在 rss 中最多生成的文章数(0显示所有)
  hub:
  content: true    #是否包含文章内容

#统计字数和阅读时长
symbols_count_time:
  symbols: true 
  time: true 
  total_symbols: true  #站点字数
  total_time: false     #站点时长

# 自定义站点内容搜索
# 需要先安装插件：
# npm install hexo-generator-search --save
search:
  path: search.xml
  field: all  # 如只想索引文章，可设置为post

# Extensions 主题设置
## Themes: https://hexo.io/themes/
theme: next

# Deployment  部署配置，将本地public目录也就是网站部署到服务器上的配置
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git # hexo3.0之后type写git
  repo: https://github.com/markLeee/markLeee.github.io.git  # 绑定github仓库
  branch: master # 默认分支
